### ISSUE TITLE
Samples not working after spring-reactor refactoring

### ISSUE THREAD

**Issue by anatollupacescu** [reactor-attic/reactor-samples#1]
$ cd reactor-samples/
$ ./gradlew install
...
FAILURE: Build failed with an exception.
- What went wrong:
  Could not resolve all dependencies for configuration ':compile'.
  > Could not find org.projectreactor:reactor-spring:2.0.0.BUILD-SNAPSHOT.
  Required by:
      org.projectreactor.springone:reactor-samples:0.2.0

after installing reactor-spring I have the following hierarchy in m2 repo:

$ ls ~/.m2/repository/org/projectreactor/spring/
reactor-spring-context/   reactor-spring-core/      reactor-spring-messaging/ reactor-spring-webmvc/

but the expected path is ~/.m2/repository/org/projectreactor/reactor-spring/

**Comment by jbrisbin** [comment]
maven coords have changed to:

```
org.projectreactor.spring:reactor-spring-context:2.0.0.BUILD-SNAPSHOT
```

there's likely to be a few minor tweaks as well. We'll try to address that shortly.

**Comment by chrissekaran** [comment]
Havent got this project to build locally and this is due to build problems from possible package re-structuring. Wondering if there has there been a fix yet

**Comment by jbrisbin** [comment]
I'll try and take a look. Maven coords have changed (again).

**Comment by songyangster** [comment]
Still not compiling.  Would it be possible to add pom.xml as well?

./gradlew compileJava
...
FAILURE: Build failed with an exception.
- What went wrong:
  Could not resolve all dependencies for configuration ':compile'.
  > Could not find io.projectreactor:reactor-stream:2.1.0.BUILD-SNAPSHOT.
  Searched in the following locations:
      file:/Users/songyang/.m2/repository/io/projectreactor/reactor-stream/2.1.0.BUILD-SNAPSHOT/maven-metadata.xml
      file:/Users/songyang/.m2/repository/io/projectreactor/reactor-stream/2.1.0.BUILD-SNAPSHOT/reactor-stream-2.1.0.BUILD-SNAPSHOT.pom
      file:/Users/songyang/.m2/repository/io/projectreactor/reactor-stream/2.1.0.BUILD-SNAPSHOT/reactor-stream-2.1.0.BUILD-SNAPSHOT.jar
      https://repo1.maven.org/maven2/io/projectreactor/reactor-stream/2.1.0.BUILD-SNAPSHOT/maven-metadata.xml
      https://repo1.maven.org/maven2/io/projectreactor/reactor-stream/2.1.0.BUILD-SNAPSHOT/reactor-stream-2.1.0.BUILD-SNAPSHOT.pom
      https://repo1.maven.org/maven2/io/projectreactor/reactor-stream/2.1.0.BUILD-SNAPSHOT/reactor-stream-2.1.0.BUILD-SNAPSHOT.jar
      http://repo.spring.io/release/io/projectreactor/reactor-stream/2.1.0.BUILD-SNAPSHOT/maven-metadata.xml
      http://repo.spring.io/release/io/projectreactor/reactor-stream/2.1.0.BUILD-SNAPSHOT/reactor-stream-2.1.0.BUILD-SNAPSHOT.pom
      http://repo.spring.io/release/io/projectreactor/reactor-stream/2.1.0.BUILD-SNAPSHOT/reactor-stream-2.1.0.BUILD-SNAPSHOT.jar
      https://jcenter.bintray.com/io/projectreactor/reactor-stream/2.1.0.BUILD-SNAPSHOT/maven-metadata.xml
      https://jcenter.bintray.com/io/projectreactor/reactor-stream/2.1.0.BUILD-SNAPSHOT/reactor-stream-2.1.0.BUILD-SNAPSHOT.pom
      https://jcenter.bintray.com/io/projectreactor/reactor-stream/2.1.0.BUILD-SNAPSHOT/reactor-stream-2.1.0.BUILD-SNAPSHOT.jar
  Required by:
      io.projectreactor.springone:reactor-samples:0.2.0

**Comment by jamalahmedmaaz** [comment]
Hi Friends,

Is anyone looking into this. facing the same issue.

FAILURE: Build failed with an exception.
- What went wrong:
  Could not resolve all dependencies for configuration ':core:compile'.
  
  > Could not find io.projectreactor:reactor-core:2.1.0.BUILD-SNAPSHOT.
  > Required by:
  >     io.projectreactor.quickstart:core:1.0.0.BUILD-SNAPSHOT
  > Could not find io.projectreactor:reactor-bus:2.1.0.BUILD-SNAPSHOT.
  > Required by:
  >     io.projectreactor.quickstart:core:1.0.0.BUILD-SNAPSHOT
  > Could not find io.projectreactor:reactor-stream:2.1.0.BUILD-SNAPSHOT.
  > Required by:
  >     io.projectreactor.quickstart:core:1.0.0.BUILD-SNAPSHOT
- Try:

After changing 

FAILURE: Build failed with an exception.
- What went wrong:
  Could not resolve all dependencies for configuration ':core:compile'.
  
  > Could not find org.projectreactor.spring:reactor-core:2.1.0.BUILD-SNAPSHOT.
  > Required by:
  >     org.projectreactor.spring.quickstart:core:1.0.0.BUILD-SNAPSHOT
  > Could not find org.projectreactor.spring:reactor-bus:2.1.0.BUILD-SNAPSHOT.
  > Required by:
  >     org.projectreactor.spring.quickstart:core:1.0.0.BUILD-SNAPSHOT
  > Could not find org.projectreactor.spring:reactor-stream:2.1.0.BUILD-SNAPSHOT.
  > Required by:
  >     org.projectreactor.spring.quickstart:core:1.0.0.BUILD-SNAPSHOT
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by cyberoblivion** [comment]
Still not compiling

**Comment by simonbasle** [comment]
This repository is not up to date, see https://github.com/reactor/reactor-core tests and https://github.com/reactor/lite-rx-api-hands-on. We're going to archive this repository for reference.
