### ISSUE TITLE
build failed issue

### ISSUE THREAD

**Issue by v71017** [reactor-attic/reactor-samples#10]
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/vpati/Intuit_2/reactor-samples/build.gradle' line: 80

* What went wrong:
A problem occurred evaluating root project 'reactor-samples'.
> Could not find method io.projectreactor.ipc:reactor-aeron:0.6.1.RELEASE() for arguments [build_aygb19ixbpe54mwnspmtn5dad$_run_closure4_closure8@260043d] on root project 'reactor-samples'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by natraj09** [comment]
Getting the same issue as reported above
```Downloading http://services.gradle.org/distributions/gradle-2.2.1-all.zip
.....................................................................................................................................................................
Unzipping /Users/nsrinivasan/.gradle/wrapper/dists/gradle-2.2.1-all/2m8005s69iu8v0oiejfej094b/gradle-2.2.1-all.zip to /Users/nsrinivasan/.gradle/wrapper/dists/gradle-2.2.1-all/2m8005s69iu8v0oiejfej094b
Set executable permissions for: /Users/nsrinivasan/.gradle/wrapper/dists/gradle-2.2.1-all/2m8005s69iu8v0oiejfej094b/gradle-2.2.1/bin/gradle

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/nsrinivasan/git/reactor-samples/build.gradle' line: 80

* What went wrong:
A problem occurred evaluating root project 'reactor-samples'.
> Could not find method io.projectreactor.ipc:reactor-aeron:0.6.1.RELEASE() for arguments [build_doabhpa6y8imted6qe8cy6haz$_run_closure4_closure8@3a0b6aff] on root project 'reactor-samples'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 17.555 secs```

**Comment by simonbasle** [comment]
This repository is not up to date, see https://github.com/reactor/reactor-core tests and https://github.com/reactor/lite-rx-api-hands-on. We're going to archive this repository for reference.
